"""initial database schema

Revision ID: d87ff820fdf5
Revises: 
Create Date: 2026-09-27 13:02:38.442718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87ff820fdf5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_foreign_key(None, 'alerts', 'detections', ['detection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'alerts', 'cameras', ['camera_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_cameras_camera_type'), 'cameras', ['camera_type'], unique=False)
    op.create_index(op.f('ix_cameras_department'), 'cameras', ['department'], unique=False)
    op.create_index(op.f('ix_cameras_is_active'), 'cameras', ['is_active'], unique=False)
    op.create_index(op.f('ix_cameras_status'), 'cameras', ['status'], unique=False)
    op.create_index(op.f('ix_cameras_zone'), 'cameras', ['zone'], unique=False)
    op.create_index(op.f('ix_detections_event_type'), 'detections', ['event_type'], unique=False)
    op.create_foreign_key(None, 'detections', 'cameras', ['camera_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_watchlist_created_at'), 'watchlist', ['created_at'], unique=False)
    op.create_index(op.f('ix_watchlist_entity_type'), 'watchlist', ['entity_type'], unique=False)
    op.create_index(op.f('ix_watchlist_is_active'), 'watchlist', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_is_active'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_entity_type'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_created_at'), table_name='watchlist')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_index(op.f('ix_detections_event_type'), table_name='detections')
    op.drop_index(op.f('ix_cameras_zone'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_status'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_is_active'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_department'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_type'), table_name='cameras')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    # ### end Alembic commands ###
